version: '3.8'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - backend

  backend:
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - frontend
      - backend

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - 8888:80
    networks:
      - frontend

volumes: 
  db:

networks:
  frontend:
  backend: